#Defines Swagger version
swagger: "2.0"
#Information displayed on the docs page
info:
  title: "Maze Game FYP -  High Score Leaderboard"
  version: "1.0"
  #Necessary for copyright
  license: 
    name: MIT




schemes:
 - http


#All the end-points for the API 
paths:
  /HelloWorld/:
    get:
      operationId: api.HelloWorld
      responses:
        '200':
          description: "Hello World"

  #Routes for top user & score        
  /todays-highscore/:
    get:
      operationId: api.scores.getTodaysHighScore
      responses:
        200:
          description: 'The top user and their score'   

  /leaderboard/:
    get:
      operationId: api.scores.getLeaderboard
      responses:
        '200':
          description: 'List of high scorers'        

  #Routes for setting the score 
  /savescore/:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: productPayload
        description: Device ID and score 
        schema:
          $ref: '#/definitions/Score'
      operationId: api.scores.setPlayerScore
      responses:
        201:
          description: Successfully added score to the leaderboard for today & all time.
        400:
          description: invalid input, object invalid


definitions:
  Score:
    type: object
    properties:
      userid: { type: string }
      score: { type: string }
  
  